import Navigation from '@/components/system/Navigation/Navigation'
import './globals.css'
import { Inria_Sans } from 'next/font/google'
import { Scrollbar } from '@/components/system/scrollbar/scrollbar'

const inria = Inria_Sans({ subsets: ['latin'],weight: ['300','400','700']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-primary-light' style={inria.style}>
        <Scrollbar elem={'body'} />
        <Navigation />
        {children}
      </body>
    </html>
  )
}
